name: emrals
description: Earn money cleaning up

version: 0.2.7+404

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.1.5
  path_provider: ^0.5.0+1
  http: 0.12.0+2
  camera: ^0.5.2+1
  cached_network_image: ^0.8.0
  location: ^2.3.5
  url_launcher: ^5.0.2
  flutter_launcher_icons: ^0.7.2
  photo_view: ^0.4.0
  intl: ^0.15.8
  barcode_scan: ^1.0.0
  font_awesome_flutter: ^8.4.0
  share: ^0.6.1+1
  share_extend: ^1.0.8
  google_maps_flutter: ^0.5.13
  sentry: ^2.2.0
  contacts_service: ^0.2.7
  qr: ^1.1.1
  firebase_messaging: ^5.0.1+1
  shared_preferences: ^0.5.2+1
  path: ^1.6.2
  #firebase_ml_vision: 0.6.0+1
  qr_mobile_vision: ^0.2.2
  flutter_udid: ^1.0.0
  flutter_pagewise: ^1.2.3
  permission_handler: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  image_path_ios: "assets/icon-iOS.png"
