name: emrals
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fancy_bottom_navigation:
  cupertino_icons: ^0.1.2
  sqflite: 
  path_provider:
  http:
  shared_preferences:
  camera: 
  cached_network_image:
  location:
  url_launcher:
  image_picker:
  flutter_launcher_icons: 
  photo_view:
  exif: 
  open_file:


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets/icon.png"