name: emrals
description: A new Flutter application.

version: 0.2.0

environment:
  sdk: ">=2.1.0-dev.9.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fancy_bottom_navigation:
  cupertino_icons: ^0.1.2
  sqflite: 1.1.0
  path_provider: 0.4.1
  http: 0.12.0+1
  camera: 0.3.0
  cached_network_image: 0.5.1
  location: 1.4.1
  url_launcher: 5.0.0
  flutter_launcher_icons:
  photo_view: 0.1.3
  intl: ">=0.14.0"
  barcode_scan: ^0.0.3
  font_awesome_flutter: 8.4.0
  share: 0.6.0+1
  google_maps_flutter:
    git:
     url: git://github.com/flutter/plugins
     path: packages/google_maps_flutter
  sentry: any
  contacts_service: ^0.1.1
  simple_permissions: ^0.1.9
  #onesignal: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"